import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hextank, HextankWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :hextank, HextankWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Only warnings and errors in production: less to write, and no request logs.
config :logger, level: :warning

# The telemetry_poller library measures the VM every few seconds by default. Nothing
# reads those numbers in production, and the timer would keep the machine busy.
config :telemetry_poller, :default, false

# The session cookie only travels over HTTPS (see HextankWeb.Endpoint).
config :hextank, :secure_cookies, true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
